FROM python:3.11-slim

WORKDIR /app

# Dépendances minimales + MLflow
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Le "command" est défini dans docker-compose.yml
